title: Yuxiang Jia's Homepage
page-top-title: Yuxiang Jia
top-section-bg-text: Computer Science and Artificial Intelligence
home-subtitle: Yuxiang Jia&ensp;|&ensp;贾玉祥
copyright-text: '&copy; Yuxiang Jia 2023-2025. All Rights Reserved.'
