title: Welcome to Yuxiang Jia's Homepage
page-top-title: 贾玉祥 | Yuxiang Jia@ZZU_NLP
top-section-bg-text: 
home-subtitle: Yuxiang Jia&ensp;|&ensp;贾玉祥
copyright-text: '&copy; Yuxiang Jia 2023-2025. All Rights Reserved.'
